### PR TITLE
BI-2799: Migrate BI Connector ODBC driver signing from legacy notary to Garasign

### PR DESCRIPTION
**Pull request by EthanHardyMongo**
This PR migrates from Notary Service to Garasign.

### CODE REVIEW

**Review by nbagnard — CHANGES_REQUESTED** [review]
Can you please migrate the Mac signing task to using Garasign too

**Comment by EthanHardyMongo** [comment]
> Can you please migrate the Mac signing task to using Garasign too

Just to be clear, the Mac signing task doesn't use Notary, but you still want me to change it to Garasign right?

**Comment by pmeredit** [comment]
> > Can you please migrate the Mac signing task to using Garasign too
> 
> Just to be clear, the Mac signing task doesn't use Notary, but you still want me to change it to Garasign right?

Correct

**Review by pmeredit — APPROVED** [review]
LGTM!

**Review by nbagnard — APPROVED** [review]
LGTM!

**Comment by EthanHardyMongo** [comment]
evergreen merge

**Pull request merged**
